-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 15:14:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_s7131322_f19
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_s7131322_f19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_s7131322_f19` DEFAULT CHARACTER SET utf8 ;
USE `db_s7131322_f19` ;

-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`AcLevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`AcLevels` (
  `idAcLevels` INT NOT NULL,
  `Level` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcLevels`),
  UNIQUE INDEX `Level_UNIQUE` (`Level` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`Courses` (
  `idCourse` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `CourseNumber` INT NOT NULL,
  `Prefix` INT NOT NULL,
  `ClassRoom` INT NOT NULL,
  `Professor` INT NOT NULL,
  PRIMARY KEY (`idCourse`),
  INDEX `idPrefixes_idx` (`Prefix` ASC),
  INDEX `idRooms_idx` (`ClassRoom` ASC),
  INDEX `idProfessors_idx` (`Professor` ASC),
  CONSTRAINT `idPrefixesToCourse`
    FOREIGN KEY (`Prefix`)
    REFERENCES `db_s7131322_f19`.`Prefixes` (`idPrefixes`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idRoomsToCourse`
    FOREIGN KEY (`ClassRoom`)
    REFERENCES `db_s7131322_f19`.`Rooms` (`idRooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProfessorsToCourse`
    FOREIGN KEY (`Professor`)
    REFERENCES `db_s7131322_f19`.`Professors` (`idProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`Departments` (
  `idDepartments` INT NOT NULL,
  `Prefix` INT NOT NULL,
  `DepartmentHead` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idDepartments`),
  INDEX `idProfessors_idx` (`DepartmentHead` ASC),
  INDEX `idPrefixes_idx` (`Prefix` ASC),
  CONSTRAINT `idPrefixesToDept`
    FOREIGN KEY (`Prefix`)
    REFERENCES `db_s7131322_f19`.`Prefixes` (`idPrefixes`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idProfessorsToDept`
    FOREIGN KEY (`DepartmentHead`)
    REFERENCES `db_s7131322_f19`.`Professors` (`idProfessors`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`Prefixes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`Prefixes` (
  `idPrefixes` INT NOT NULL,
  `Prefix` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idPrefixes`),
  UNIQUE INDEX `Prefix_UNIQUE` (`Prefix` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`Professors` (
  `idProfessors` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Department` VARCHAR(45) NOT NULL,
  `Phone` INT(11) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idProfessors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`Rooms` (
  `idRooms` INT NOT NULL,
  `Building` VARCHAR(20) NOT NULL,
  `RoomNumber` INT NOT NULL,
  `Capacity` INT NOT NULL,
  PRIMARY KEY (`idRooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`StudentToCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`StudentToCourse` (
  `StudentID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  PRIMARY KEY (`StudentID`, `CourseID`),
  INDEX `idCourse_idx` (`CourseID` ASC),
  CONSTRAINT `idStudents`
    FOREIGN KEY (`StudentID`)
    REFERENCES `db_s7131322_f19`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCourse`
    FOREIGN KEY (`CourseID`)
    REFERENCES `db_s7131322_f19`.`Courses` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_s7131322_f19`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_s7131322_f19`.`Students` (
  `idStudents` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `AcLevel` INT NOT NULL DEFAULT 1,
  `GPA` DECIMAL(2) NOT NULL,
  `EmergencyContact` INT(11) NULL,
  PRIMARY KEY (`idStudents`),
  INDEX `idAcLevels_idx` (`AcLevel` ASC),
  CONSTRAINT `idAcLevelsToStudent`
    FOREIGN KEY (`AcLevel`)
    REFERENCES `db_s7131322_f19`.`AcLevels` (`idAcLevels`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
